const BASE_FILTER = `
  LISTING_JOB_CLASSIFICATION_REGION IN ('AVC | V4 - UK', 'AVB - UK')
`;

export const CORE_METRICS_SQL = `
  SELECT
    COUNT(*) as jobs,
    SUM(LISTING_TTV) as ttv,
    AVG(LISTING_TTV) as avg_ttv,
    SUM(AV_FEE) as av_fee,
    ROUND(SUM(AV_FEE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as margin_pct,
    SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) as alloc_spend,
    ROUND(SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as spend_ttv_pct
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_COMPLETION_STATUS = 'Completed Paid'
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
`;

export const CANCELLATIONS_SQL = `
  SELECT
    SUM(CASE
      WHEN DAYS_FROM_CANCELLATION_TO_PICK_UP IN (0, -1)
      THEN 1 ELSE 0
    END) as otd_cancels,
    SUM(CASE
      WHEN CANCELLATION_REASON = 'av_couldnt_source_a_tp'
      THEN 1 ELSE 0
    END) as cant_source,
    SUM(CASE
      WHEN LISTING_ALLOCATION_STATUS = 'Third Party Cancelled'
      THEN 1 ELSE 0
    END) as tp_cancels
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
`;

export const DEALLOCATIONS_SQL = `
  SELECT
    COUNT(*) as total_rows,
    SUM(OTD_DEALLOCATION_COUNT) as total_deallocations,
    ROUND(SUM(OTD_DEALLOCATION_COUNT) / NULLIF(COUNT(*), 0) * 100, 2) as otd_deallo_pct,
    COUNT(CASE WHEN OTD_DEALLOCATION_COUNT > 0 THEN 1 END) as rows_with_deallocations
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
`;

export const OTD_ALLOC_SPEND_SQL = `
  SELECT
    COUNT(*) as count,
    ROUND(SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE), 2) as alloc_spend
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND OTD_DEALLOCATION_COUNT > 0
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
`;

export const OTD_NO_SPEND_SQL = `
  SELECT
    COUNT(*) as count,
    SUM(CASE
      WHEN ALLOCATION_SPEND_TP_AMOUNT_CHANGE IS NULL
        OR ALLOCATION_SPEND_TP_AMOUNT_CHANGE = 0
      THEN 1 ELSE 0
    END) as no_spend,
    ROUND(SUM(CASE
      WHEN ALLOCATION_SPEND_TP_AMOUNT_CHANGE IS NULL
        OR ALLOCATION_SPEND_TP_AMOUNT_CHANGE = 0
      THEN 1 ELSE 0
    END) / NULLIF(COUNT(*), 0) * 100, 2) as no_spend_pct
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_COMPLETION_STATUS = 'Completed Paid'
    AND DAYS_FROM_ALLOCATION_TO_PICKUP = 0
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
`;

export const CATEGORY_BREAKDOWN_SQL = `
  SELECT
    LISTING_CATEGORY_NAME as category,
    COUNT(*) as jobs,
    SUM(LISTING_TTV) as ttv,
    ROUND(SUM(AV_FEE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as margin_pct,
    SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) as alloc_spend,
    ROUND(SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as spend_ttv_pct
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_COMPLETION_STATUS = 'Completed Paid'
    AND LISTING_CATEGORY_NAME IN ('Furniture', 'Home Removal', 'Car', 'Motorbike', 'Piano')
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
  GROUP BY LISTING_CATEGORY_NAME
  ORDER BY jobs DESC
`;

export const REGIONAL_BREAKDOWN_SQL = `
  SELECT
    LISTING_NUTS1_REGION as region,
    COUNT(*) as jobs,
    SUM(LISTING_TTV) as ttv,
    ROUND(SUM(AV_FEE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as margin_pct,
    SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) as alloc_spend,
    ROUND(SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as spend_ttv_pct
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_COMPLETION_STATUS = 'Completed Paid'
    AND LISTING_PICK_UP_DATE >= ?
    AND LISTING_PICK_UP_DATE < ?
  GROUP BY LISTING_NUTS1_REGION
  ORDER BY jobs DESC
`;

export const TRENDS_SQL = `
  SELECT
    DATE_TRUNC('month', LISTING_PICK_UP_DATE) as period,
    SUM(CASE
      WHEN LISTING_COMPLETION_STATUS = 'Completed Paid'
      THEN 1 ELSE 0
    END) as jobs,
    SUM(LISTING_TTV) as ttv,
    SUM(AV_FEE) as av_fee,
    ROUND(SUM(AV_FEE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as margin_pct,
    SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) as alloc_spend,
    ROUND(SUM(ALLOCATION_SPEND_TP_AMOUNT_CHANGE) / NULLIF(SUM(LISTING_TTV), 0) * 100, 2) as spend_ttv_pct,
    SUM(CASE
      WHEN DAYS_FROM_CANCELLATION_TO_PICK_UP IN (0, -1)
      THEN 1 ELSE 0
    END) as otd_cancels,
    SUM(CASE
      WHEN LISTING_ALLOCATION_STATUS = 'Third Party Cancelled'
      THEN 1 ELSE 0
    END) as tp_cancels,
    SUM(CASE
      WHEN CANCELLATION_REASON = 'av_couldnt_source_a_tp'
      THEN 1 ELSE 0
    END) as cant_source_count,
    SUM(OTD_DEALLOCATION_COUNT) as otd_deallocations,
    COUNT(*) as total_records
  FROM MART_ENTERPRISE.PRODUCTION.ENTERPRISE_LISTING_EXTRACT
  WHERE ${BASE_FILTER}
    AND LISTING_PICK_UP_DATE >= DATEADD('month', -13, DATE_TRUNC('month', CAST(? AS DATE)))
    AND LISTING_PICK_UP_DATE <= DATE_TRUNC('month', CAST(? AS DATE))
  GROUP BY DATE_TRUNC('month', LISTING_PICK_UP_DATE)
  ORDER BY period ASC
`;
